Fix GHA for release branch

diff --git a/.github/require_release_branch.yml b/.github/require_release_branch.yml
--- a/.github/require_release_branch.yml
+++ b/.github/require_release_branch.yml
@@ -8,17 +8,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check branch
-        if: github.base_ref == 'master' && github.head_ref != 'dev'
+        if: github.base_ref == 'main' && github.head_ref != 'dev'
         run: |
-          echo "ERROR: You can only merge to master from dev. Contributors should point their PRs to the dev branch."
+          echo "ERROR: You can only merge to main from dev. Contributors should point their PRs to the dev branch."
           exit 1
           
       - uses: actions/checkout@v3
-        if: github.base_ref == 'master'
+        if: github.base_ref == 'main'
         with:
           fetch-depth: 0
           
       - name: Check version.py
-        if: github.base_ref == 'master'
+        if: github.base_ref == 'main'
         run: |
-          git diff --name-only origin/master | grep -q RGBMatrixEmulator/version.py || (echo "Need to change version for pushes to master!" && exit 1)
+          git diff --name-only origin/main | grep -q RGBMatrixEmulator/version.py || (echo "Need to change version for pushes to master!" && exit 1)
